### ISSUE TITLE
Azure Bot Service - No such file or directory \.funcpack\types\mime.types

### ISSUE THREAD

**Issue by chitrang89** [Azure/azure-functions-pack#22] opened 2017-04-29 03:39 UTC
I started receiving ﻿error as shown in the image. I have tried to restart the appservice, push a change to trigger a new deployment but still no go. Could I please get some help here?

Error Log:

2017-04-29T02:59:31.056 Exception while executing function: Functions.messages. mscorlib: Error: ENOENT: no such file or directory, open 'D:\home\site\wwwroot\.funcpack\types\mime.types'

    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Mime.module.exports.Mime.load (D:\home\site\wwwroot\.funcpack\index.js:48182:20)
    at Object.<anonymous> (D:\home\site\wwwroot\.funcpack\index.js:48218:6)
    at __webpack_require__ (D:\home\site\wwwroot\.funcpack\index.js:21:30)
    at Object.<anonymous> (D:\home\site\wwwroot\.funcpack\index.js:809850:12)
    at __webpack_require__ (D:\home\site\wwwroot\.funcpack\index.js:21:30)
    at Object.<anonymous> (D:\home\site\wwwroot\.funcpack\index.js:810958:19)
    at __webpack_require__ (D:\home\site\wwwroot\.funcpack\index.js:21:30).

**Comment by davidebbo** [comment] 2017-04-29 04:22
There is a new version of Kudu that may be causing this.

As a temporary workaround, create an Azure App Setting names `KUDU_EXTENSION_VERSION`, with value `62.60413.2788`. This will go back to the old version.

But we need to investigate. Would you be able to [share a repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) so that we can repro and take a look? Thanks!

**Comment by davidebbo** [comment] 2017-04-29 04:23
Adding @watashiSHUN as well.

**Comment by chitrang89** [comment] 2017-04-29 04:24
Hi David,

Thanks for  your prompt reply. Could you please share the respective email address/es as my repo is not on GitHub.

**Comment by davidebbo** [comment] 2017-04-29 04:30
Sure, it's david.ebbo (at) microsoft.com.

Please start by verifying that issue goes away with older Kudu.

**Comment by watashiSHUN** [comment] 2017-04-29 04:30
cc to shucai (at) microsoft.com, thanks

**Comment by chitrang89** [comment] 2017-04-29 04:36
Can confirm that the issue is related to the new release as setting the KUDU version as per @davidebbo seems to fix the issue. Will share repository now. Thanks guys :)

**Comment by chitrang89** [comment] 2017-04-29 04:44
Also, I did a smoke test by creating a new bot which worked fine until I added CD with the same source and it started complaining, could it be that something in my source triggers the new version of KUDU?

**Comment by watashiSHUN** [comment] 2017-04-29 04:46
I can't access the repository:

> The owner of this repository is already at their plan limit and will need to upgrade before adding more users.

Can you share your function app [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)?

**Comment by davidebbo** [comment] 2017-04-29 04:51
I'm done for the day, but will try to help look over the weekend.

**Comment by watashiSHUN** [comment] 2017-04-29 04:54
just reading the error message it feels like in your index.js you are trying to access `index\..\types\mime.types` but the new kudu will move your index.js into a new folder called `.funcpack` (and smash it with its dependencies)

can you try to use an absolute path as a workaround? (no need to change kudu version)

**Comment by davidebbo** [comment] 2017-04-30 18:21
@chitrang89 I see you shared the repo with me to my microsoft email. Bitbucket is asking me to create a new account to access it. Could you revoke that one and instead share to user 'davidebbo'? Or as an alternative, you can share the name of a test Azure Web App that is in that state.

**Comment by davidebbo** [comment] 2017-04-30 19:19
Ok, so I investigated, and I think I understand the root cause: the new deployment process relies on WebPack, and one of the npm modules you are using (mime) is not friendly to WebPack. I see a mention of a similar issue on https://github.com/visionmedia/superagent/issues/1036.

Let's figure out how we can unblock this.

**Comment by davidebbo** [comment] 2017-05-01 19:18
@chitrang89 a fix has been deployed to not have this new mode on by default. Can you try removing `KUDU_EXTENSION_VERSION` and making sure it still all works? Thanks!

**Comment by christopheranderson** [comment] 2017-07-06 16:32
I've now added support for ignoring modules. You should be able to list "mime" as an ignored module.

**Closed by christopheranderson** 2017-07-06 16:32 UTC
